#!/bin/sh
#

# TODO add the folloing steps:
# Check existance .gitignore
# Check existance excluded data directory in .gitignore
# Check existance on FS of the excluded data directory
# Start the implementation of the JIRA-task in the order found in 
# sub-tasks of RDMR-373
echo "Calling from precommit works."
